WITH 
ETL AS
(SELECT TABLE_NAME,COLUMN_NAME
FROM USER_TAB_COLS
WHERE TABLE_NAME = 'MBTC_DEV_CLNTACCNT_BNFCRS_MASTER'),
TPMS AS
(SELECT TABLE_NAME,COLUMN_NAME
FROM USER_TAB_COLS
WHERE TABLE_NAME = 'WM_CLIENTNOMINEE')
SELECT E.COLUMN_NAME,
  (CASE WHEN T.COLUMN_NAME IS NOT NULL THEN 1 ELSE 0 END) AS MATCH_FOUND
FROM ETL E
  LEFT JOIN TPMS T
    ON (E.COLUMN_NAME = T.COLUMN_NAME)
WHERE E.COLUMN_NAME <> 'ROW_NUM'